modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CakeChomps/issues"
displayURL="https://minecraft.curseforge.com/projects/cake-chomps"
logoFile="cake_chomps_icon.png"
authors="C4"
[[mods]]
modId="cakechomps"
version="${file.jarVersion}"
displayName="Cake Chomps"
description='''
Adds sound and crumb particles when you eat cake.
'''
[[dependencies.comforts]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.comforts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"